[package]
name = "range"
version = "0.0.0"
authors = ["Antonio Villagra De La Cruz"]
license = "MIT"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3.55"
